package com.jeffdisher.laminar.avm;

import java.util.List;
import java.util.UUID;

import org.junit.Assert;
import org.junit.Test;

import com.jeffdisher.laminar.contracts.DoNothing;
import com.jeffdisher.laminar.contracts.EmulateStutter;
import com.jeffdisher.laminar.contracts.SimpleDeployment;
import com.jeffdisher.laminar.types.TopicName;
import com.jeffdisher.laminar.types.event.EventRecord;
import com.jeffdisher.laminar.types.payload.Payload_KeyDelete;
import com.jeffdisher.laminar.types.payload.Payload_KeyPut;


public class TestAvm {
	@Test
	public void testStartStop() throws Throwable {
		// We just write out this JAR for testing later on (since integration can't use this AVM helper.
		AvmBridge bridge = new AvmBridge();
		bridge.shutdown();
	}

	@Test
	public void testDoNothing() throws Throwable {
		byte[] key = new byte[32];
		key[15] = 42;
		byte[] code = ContractPackager.createJarForClass(DoNothing.class);
		
		long termNumber = 1L;
		long globalOffset = 1L;
		long initialLocalOffset = 1L;
		UUID clientId = UUID.randomUUID();
		long clientNonce = 1L;
		
		TopicName topic = TopicName.fromString("test");
		byte[] value = new byte[] {1,2,3};
		AvmBridge bridge = new AvmBridge();
		
		TopicContext context = new TopicContext();
		List<EventRecord> records = bridge.runCreate(context, termNumber, globalOffset, initialLocalOffset, clientId, clientNonce, topic, code, new byte[0]);
		// No events generated by the contract on deployment.
		Assert.assertEquals(0, records.size());
		Assert.assertNotNull(context.transformedCode);
		Assert.assertNotNull(context.objectGraph);
		globalOffset += 1;
		clientNonce += 1;
		initialLocalOffset += records.size();
		
		// Sending a PUT or DELETE will do nothing - results in no events.
		records = bridge.runPut(context, termNumber, globalOffset, initialLocalOffset, clientId, clientNonce, topic, key, value);
		Assert.assertEquals(0, records.size());
		globalOffset += 1;
		clientNonce += 1;
		initialLocalOffset += records.size();
		
		// A DELETE should result in 1 event for that key.
		records = bridge.runDelete(context, termNumber, globalOffset, initialLocalOffset, clientId, clientNonce, topic, key);
		Assert.assertEquals(0, records.size());
		globalOffset += 1;
		clientNonce += 1;
		initialLocalOffset += records.size();
		
		bridge.shutdown();
	}

	@Test
	public void testSimpleDeployment() throws Throwable {
		byte[] key = new byte[32];
		key[31] = 1;
		byte[] code = ContractPackager.createJarForClass(SimpleDeployment.class);
		byte[] arguments = key;
		
		long termNumber = 1L;
		long globalOffset = 1L;
		long initialLocalOffset = 1L;
		UUID clientId = UUID.randomUUID();
		long clientNonce = 1L;
		
		TopicName topic = TopicName.fromString("test");
		AvmBridge bridge = new AvmBridge();
		
		TopicContext context = new TopicContext();
		List<EventRecord> records = bridge.runCreate(context, termNumber, globalOffset, initialLocalOffset, clientId, clientNonce, topic, code, arguments);
		Assert.assertEquals(1, records.size());
		Assert.assertEquals(0, ((Payload_KeyPut)records.get(0).payload).value[0]);
		Assert.assertNotNull(context.transformedCode);
		Assert.assertNotNull(context.objectGraph);
		
		bridge.shutdown();
	}

	@Test
	public void testDeploymentPutAndDelete() throws Throwable {
		byte[] key = new byte[32];
		key[31] = 2;
		byte[] code = ContractPackager.createJarForClass(SimpleDeployment.class);
		byte[] arguments = key;
		
		long termNumber = 1L;
		long globalOffset = 1L;
		long initialLocalOffset = 1L;
		UUID clientId = UUID.randomUUID();
		long clientNonce = 1L;
		
		TopicName topic = TopicName.fromString("test");
		byte[] value = new byte[] {1,2,3};
		AvmBridge bridge = new AvmBridge();
		
		TopicContext context = new TopicContext();
		List<EventRecord> records = bridge.runCreate(context, termNumber, globalOffset, initialLocalOffset, clientId, clientNonce, topic, code, arguments);
		Assert.assertEquals(1, records.size());
		Assert.assertEquals(0, ((Payload_KeyPut)records.get(0).payload).value[0]);
		Assert.assertNotNull(context.transformedCode);
		Assert.assertNotNull(context.objectGraph);
		globalOffset += 1;
		clientNonce += 1;
		initialLocalOffset += records.size();
		
		records = bridge.runPut(context, termNumber, globalOffset, initialLocalOffset, clientId, clientNonce, topic, key, value);
		Assert.assertEquals(1, records.size());
		Assert.assertEquals(1, ((Payload_KeyPut)records.get(0).payload).value[0]);
		globalOffset += 1;
		clientNonce += 1;
		initialLocalOffset += records.size();
		
		records = bridge.runDelete(context, termNumber, globalOffset, initialLocalOffset, clientId, clientNonce, topic, key);
		Assert.assertEquals(1, records.size());
		Assert.assertEquals(2, ((Payload_KeyPut)records.get(0).payload).value[0]);
		globalOffset += 1;
		clientNonce += 1;
		initialLocalOffset += records.size();
		
		bridge.shutdown();
	}

	@Test
	public void testEmulatedStutter() throws Throwable {
		byte[] key = new byte[32];
		key[15] = 42;
		byte[] code = ContractPackager.createJarForClass(EmulateStutter.class);
		
		long termNumber = 1L;
		long globalOffset = 1L;
		long initialLocalOffset = 1L;
		UUID clientId = UUID.randomUUID();
		long clientNonce = 1L;
		
		TopicName topic = TopicName.fromString("test");
		byte[] value = new byte[] {1,2,3};
		AvmBridge bridge = new AvmBridge();
		
		TopicContext context = new TopicContext();
		List<EventRecord> records = bridge.runCreate(context, termNumber, globalOffset, initialLocalOffset, clientId, clientNonce, topic, code, new byte[0]);
		// No events generated by the contract on deployment.
		Assert.assertEquals(0, records.size());
		Assert.assertNotNull(context.transformedCode);
		Assert.assertNotNull(context.objectGraph);
		globalOffset += 1;
		clientNonce += 1;
		initialLocalOffset += records.size();
		
		// A PUT should result in 2 events with the same key and value.
		records = bridge.runPut(context, termNumber, globalOffset, initialLocalOffset, clientId, clientNonce, topic, key, value);
		Assert.assertEquals(2, records.size());
		Assert.assertArrayEquals(key, ((Payload_KeyPut)records.get(0).payload).key);
		Assert.assertArrayEquals(value, ((Payload_KeyPut)records.get(0).payload).value);
		Assert.assertArrayEquals(key, ((Payload_KeyPut)records.get(1).payload).key);
		Assert.assertArrayEquals(value, ((Payload_KeyPut)records.get(1).payload).value);
		globalOffset += 1;
		clientNonce += 1;
		initialLocalOffset += records.size();
		
		// A DELETE should result in 1 event for that key.
		records = bridge.runDelete(context, termNumber, globalOffset, initialLocalOffset, clientId, clientNonce, topic, key);
		Assert.assertEquals(1, records.size());
		Assert.assertArrayEquals(key, ((Payload_KeyDelete)records.get(0).payload).key);
		globalOffset += 1;
		clientNonce += 1;
		initialLocalOffset += records.size();
		
		bridge.shutdown();
	}
}
