name: Laminar CI

on: [push]

env:
  WRAPPER_VERBOSE: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml
